[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "changelog"
  name = "Changelog"
  url = "changelog"
  weight = 2

[[main]]
  identifier = "contribution"
  name = "Contribution"
  url = "docs/contribution"
  weight = 3

[[main]]
  identifier = "download"
  name = "Download"
  url = "download"
  weight = 4

[[main]]
  identifier = "sourcecode"
  name = "GitHub"
  url = "https://github.com/alibaba/git-repo-go"
  weight = 5

