baseURL = "http://git-repo.info"

languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "git-repo"
theme = "techdoc"

# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = true

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "client tool for git centralized workflow (Aone or gerrit)"
    #github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    #version = "0.2.2"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    #github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"

    # Analytic section
    #google_analytics_id = "" # Your Google Analytics tracking id
    #tag_manager_container_id = "" # Your Google Tag Manager container id
    #google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "blog", "entry", "post", "posts", "download"]


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/index.html"
    weight = 1

[[menu.main]]
    name = "Download"
    url = "https://github.com/aliyun/git-repo-go/releases"
    weight = 20

[[menu.main]]
    name = "ChangeLog"
    url = "/CHANGELOG.html"
    weight = 40

[[menu.main]]
    name = "Contribution"
    url = "/contribution.html"
    weight = 60

[[menu.main]]
    name = "Issue"
    url = "https://github.com/aliyun/git-repo-go/issues"
    weight = 80

[[menu.main]]
    name = "Source code"
    url = "https://github.com/aliyun/git-repo-go"
    weight = 90
